Dump UEFI module name and type in json
binarly-io/efiXplorer pull request #91
Opened 2024-09-12 06:59 UTC by TakahiroHaruyama

Add dumping UEFI module name/type in JSON format. The data will be utilized by the new fwhunt plugin.
I don't rush at all about this merge.

2024-09-24 16:34 UTC, yeggor requested changes

2024-09-24 16:34 UTC, yeggor commented on efiXloader/uefitool.cpp
> +    out.replace_extension("").replace_extension(".mod_types.json");
better to dump this information as part of `.images.json` (`.modules.json`) and then update dependencies builder in efixplorer that is currently using `.images.json`. Let's do it after the release of IDA 90 and the corresponding efixplorer update

2024-10-04 08:16 UTC, TakahiroHaruyama commented on efiXloader/uefitool.cpp
> +    out.replace_extension("").replace_extension(".mod_types.json");
I merged the master update for IDA9 then changed the code to add module type into *.images.json instead of creating *.mod_types.json. Please check.

2024-10-05 01:51 UTC, yeggor commented on efiXloader/uefitool.cpp
> +    out.replace_extension("").replace_extension(".mod_types.json");
thanks! I've checked it and it works fine, although there are a few things I'd like to fix before merging this:
- I think it will be clearer to store it in more readable format (`{ "name": name, "kind": kind }` instead of `[name, kind]`), for example:

  ```json
  "FA20568B-548B-4B2B-81EF-1BA08D4A3CEC": {
    "kind": "DXE driver",
    "name": "BootScriptExecutorDxe"
  },
  "FAB5D4F4-83C0-4AAF-8480-442D11DF6CEA": {
    "kind": "DXE driver",
    "name": "VirtioScsiDxe"
  }
  ```
- Since we are reading the data to build a sequence of module executions from a file (which may be corrupted/outdated), we should handle exceptions (this is not related to this PR, but better add it here)

I'll add these changes and merge.

2024-10-05 01:59 UTC, yeggor approved these changes

2024-10-05 01:59 UTC, merged

2024-10-07 01:50 UTC, TakahiroHaruyama commented
Thanks for the improvement and merging :-) I completely agree with you.